name: lora-nf
channels:
  - defaults
dependencies:
  - pytorch
  - torchvision 
  - torchaudio
  - numpy
  - packaging
  - pip
  - python
  - pip:
      - PyMCubes
      - imageio
      - trimesh
      - pysdf